apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xojn2du0p-nodejs 
  janus-idp.io/tekton: xojn2du0p-nodejs
  backstage.io/kubernetes-id: xojn2du0p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xojn2du0p-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml