apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xojn2du0p-nodejs-gitops
  description: This is GitOps manifest for xojn2du0p-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=xojn2du0p-nodejs
    backstage.io/kubernetes-id: xojn2du0p-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xojn2du0p-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xojn2du0p-nodejs
